[book]
title = "海塞姆科技文档"
authors = ["haytham-ai", "PJ568"]
language = "zh"
description = "深圳市海塞姆科技有限公司在线文档维基 Wiki"

[build]
# 若目录指向的文件不存在，编译时报错
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
additional-css = ["assets/css/override.css"]
additional-js = ["assets/js/override.js"]
# 在网页右上角显示 Git 仓库链接
git-repository-url = "https://github.com/haytham-ai/public-docs"
# 在网页右上角显示对应页面的编辑按钮
edit-url-template = "https://github.com/haytham-ai/public-docs/edit/master/{path}"

# 禁用默认折叠目录：启用会导致目录的文档标题子目录失效
# [output.html.fold]
# enable = true
# level = 0

[output.html.playground]
copyable = true
